- name: download consul
  get_url: url=https://dl.bintray.com/mitchellh/consul/0.5.0_linux_amd64.zip dest=/tmp/consul.zip validate_certs=no
  sudo: yes
- name: install unzip
  apt: name=unzip=6.0-9ubuntu1.3 state=present
  sudo: yes
- name: unarchive consul.zip
  unarchive: src=/tmp/consul.zip dest=/usr/local/bin copy=no
  sudo: yes
- name: create consul group
  group: name=consul state=present
  sudo: yes
- name: create consul user
  user: name=consul state=present group=consul groups=sudo
  sudo: yes
- name: add nopasswd for user consul
  lineinfile: "dest=/etc/sudoers state=present line='consul   ALL=(ALL:ALL) NOPASSWD: ALL' validate='visudo -cf %s'"
  sudo: yes
